title: SIRIS Engineering Practices Guide

styles:
  - /assets/css/styles.css

exclude:
  - vendor
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - go
  - copy-template

#theme: uswds-jekyll

include: 
  - .rubocop.yml # in _pages/ruby

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

collections:
  pages:
    output: true
    permalink: /:path/

markdown: kramdown

sass:
  style: compressed

# Author/Organization info to be displayed in the templates
author:
  name: SIRIS Academic
  url: http://www.sirisacademic.com

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/SIRIS Logo RGB-01.png
logoalt: SIRIS Academic logo

repo:
  name: SIRIS Engineering Practices Guide
  description: Main repository
  url: https://github.com/sirisacademic/development-guide

back_link:
  url: "http://www.sirisacademic.com"
  text: SIRIS Academic website
